int getch_(void);
void math(char* s);
int getop(char* s);
double pop(void);
void push(double f);
void peek(void);
void dupe(void);
void swap(void);
void clear(void);
void rpn(void);
void build_string();
